# Este flujo de trabajo se desencadena en los envíos al repositorio.
on: [push]

jobs:
  build:
    # El nombre del archivo es Greeting
    name: Build
    # Este archivo se ejecuta en Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm scripts
      run: |
        npm install
        npm run build
